{% set version = "3.0.0" %}

package:
  name: googletrans
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/googletrans/googletrans-{{ version }}.tar.gz
  sha256: 44caeea42d91ff6ead5c2d49db2b88de66c45c2fe874c8ec03eb9b4ceb3a533d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - requests
  run:
    - python
    - requests

test:
  imports:
    - googletrans


about:
  home: https://github.com/ssut/py-googletrans
  license: MIT
  license_file: LICENSE
  summary: Free Google Translate API for Python. Translates totally free of charge
  description: "Googletrans is a free and unlimited python library that implemented Google Translate API. This uses the Google Translate Ajax API to make calls to such methods as detect and translate.\nCompatible with Python 2.7+ and 3.4+. (Note: Python 2 support will be dropped in the next major release.)"
  doc_url: https://github.com/ssut/py-googletrans
  dev_url: https://py-googletrans.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - SekouD
