appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zHyXTsPwOASKceDUElf87yqB9IMbBdzVBwWsO25/Kb2R3QElQbkv9CtbfG8usYUn1P+U5bnPy5ZynM5gHG0BjamXWhTl5X73nmhN8tIMXAJvKEQM1dZYYLqFp+EDgge5+RnAvXHqZtIqBLPSufBCPpWd0rDnNoODYrnua1TBzVXjnj6YA9F0z15bVNmmyq71XU+2Bihj3iNS9qrUVIP2h2vT/lIclvq7rVfxsPKsFSicVRGDd6/LmN31Er60psbYkgNZYbVgLIDWWaHTSzlmua0/8rIPcqdxDM2XtcjwayadQ1sVcBYOoIuf1DKY/cj47D0SyD9x47VehdrC336Z4Kla2h9ONH27TIIiATJSIECsvxfyPIK2r3VHJpFZa/Z6lhSQDX3nT+vrOEuWo+Jg7VaMQNcjjRh9OrnkX4VceEY/TfMdZVySatiBVvsmcwl/4L3nlngLNngjgimpWqQYdiHQyQJJihz4WBaFkGKLw9IJomstl6BN6kTCZXecHcjjS5j8OTQiyCGsMb/rEd6ejf0Q4uz0R5rGja2odHQknHlzmYKy2v35Di2bkN6HyW1Lgh865vt4UIYQtG/XdJXSohgEVThmnuhylbQ0Q7rmSuK2k8WK8ipmlUzWKUMqShTZujEXb36l+snVaMMg+I2CRU6Mn0ncNvIdzqJC1YulhjI=}
